controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    forward_command_controller_position:
      type: forward_command_controller/ForwardCommandController

    joint_state_controller:
      type: joint_state_controller/JointStateController

    ur_controllers:
      type: ur_controllers/ForceTorqueStateController

forward_command_controller_position:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position

ur_controllers:
  ros__parameters:
    sensor_name: tcp_fts_sensor
    state_interface_names:
      - fx
      - tz
    frame_id: rrbot_tcp
    lower_limits: -100
    upper_limits: 100
