controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    forward_command_controller_position:
      type: forward_command_controller/ForwardCommandController

    fts_controllers:
      type: force_torque_sensor_controller/ForceTorqueSensorController

    joint_state_controller:
      type: joint_state_controller/JointStateController

forward_command_controller_position:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position

fts_controllers:
  ros__parameters:
    sensor_name: tcp_fts_sensor
    interface_names:
      - fx
      - tz
    frame_id: rrbot_tcp
